# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 08e8b92
_src_path: gh:schwallergroup/copier-liac-minimal
author_email: tannous.j.majd@gmail.com
author_name: Majd Tannous
github_org: MajdTannous3579
package_name: retrochem
project_name: RetroChem
short_description: Final Project For Practical Programming in Chemistry
